pipeline {
    agent any
    stages {
        stage("stage 1") {
            steps {
                sh "echo 'This is stage 1'"
            }
        }

        stage("stage 2") {
            steps {
                echo "This is stage 2" // echo can be used directly
            }
        }

        stage("stage 3") {
            steps {
                sh "echo 'This is stage 3'"
            }
        }

        stage("stage 4") {
            steps {
                echo 'Tested poll SCM' // echo can be used like this also
            }
        }

        stage("stage 5") {
            steps {
                echo "Tested multi branch plugin"
            }
        }
    }
}
