pipeline {
    agent any

    parameters{
        string(defaultValue: "non-prod", description: "which environment to host the deployment?", name:"envType")
    }

    stages {
        stage("demo") {
            steps {
                echo "string is set to ${params.envType}"
            }
        }
    }
}